# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
#wann die Jobs durchgeführt werden sollen
on:
  push:
    branches: [ main ]
    
jobs:
  build:
            #um was für einen Server handelt es sich
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    #default
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    #bis hier ci = clean install
    - run: npm i
    - run: npm run build --if-present #durchlaufe das build scrpit, wenn eines definiert ist
    - run: npm test #zum starten der Tests
